// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpuPlD4sRz29gCqdE1wcwgpd0UXXNCig',
    appId: '1:636068903371:web:c08f17c2ff7c8b1aa3de4e',
    messagingSenderId: '636068903371',
    projectId: 'farmerpoint-99c6c',
    authDomain: 'farmerpoint-99c6c.firebaseapp.com',
    storageBucket: 'farmerpoint-99c6c.appspot.com',
    measurementId: 'G-MK5Z5R9SD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn6MpEPKiNDIIvyqLaWmE_M7zylZyvKJ4',
    appId: '1:636068903371:android:f2584b29ad975b76a3de4e',
    messagingSenderId: '636068903371',
    projectId: 'farmerpoint-99c6c',
    storageBucket: 'farmerpoint-99c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUOo_lXNSGOieuJZvZqICTaXuC0ZP97pA',
    appId: '1:636068903371:ios:af76d8b6973023c9a3de4e',
    messagingSenderId: '636068903371',
    projectId: 'farmerpoint-99c6c',
    storageBucket: 'farmerpoint-99c6c.appspot.com',
    iosBundleId: 'com.example.farmerpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUOo_lXNSGOieuJZvZqICTaXuC0ZP97pA',
    appId: '1:636068903371:ios:af76d8b6973023c9a3de4e',
    messagingSenderId: '636068903371',
    projectId: 'farmerpoint-99c6c',
    storageBucket: 'farmerpoint-99c6c.appspot.com',
    iosBundleId: 'com.example.farmerpoint',
  );
}
